# This file is auto-generated by sync_excel.py

SOIL_TYPES = ['DRC', 'Tropical lowland', 'Moist', 'Spodic soils', 'Implemetation phase', 'Capitalization phase', 'Total duration of calculation']
CLIMATES = ['DRC', 'Tropical lowland', 'Moist', 'Spodic soils', 'Implemetation phase', 'Capitalization phase', 'Total duration of calculation']
MOISTURES = ['DRC', 'Tropical lowland', 'Moist', 'Spodic soils', 'Implemetation phase', 'Capitalization phase', 'Total duration of calculation']

# Format: {Crop Name: (AGB, BGB, Soil)}
AGRI_CROP_DATA = {
    'Genetic Crop (Fallback)': (0, 0, 0),
}
